title = "Crestwood Painting"
baseURL = "https://www.crestwoodpainting.com/"
paginate = 10
googleAnalytics = "UA-1372967-1"
enableRobotsTXT = false
[taxonomies]
category = "categories"
categories = "interior", "exterior", "cabinets", "commercial"
tag = "tags"
tags = "Products", "Tips", "Color", Best Practices"
disableKinds = ['robotsTXT', 'RSS']