title = "Crestwood Painting"
baseURL = "https://www.crestwoodpainting.com/"
paginate = 10
googleAnalytics = "UA-1372967-1"
enableRobotsTXT = false
[taxonomies]
category = "categories"
- interior
- exterior
- cabinets
- commercial
tag = "tags"
- products
- tips
- color
- best practices
disableKinds:
- robotsTXT
- RSS