title = "Crestwood Painting"
baseURL = "https://crestwoodpainting.com/"
pagination.pagerSize = 10
timeout = "100s"
enableEmoji = true
googleAnalytics = "G-Y229K0TNJR"
# old G (before '24) analytics: UA-1372967-1
disableHugoGeneratorInject = true
[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true 

[params]
license_url = "https://crestwoodpainting.com/licensing/"
acquire_license_url = "mailto:admin@crestwoodpainting.com"      

[taxonomies]
category = "categories"
# tag = "tags"
# tags = ["Products", "Tips", "Color", "Best Practices"]

disableKinds = ['RSS']
enableRobotsTXT = true

[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'static'
target = 'assets'

[related]
threshold = 30
includeNewer = true
toLower = true

[[related.indices]]
name = "keywords"
weight = 100

[[related.indices]]
name = "categories"
weight = 80

[[related.indices]]
name = "date"
weight = 10
