title = "Crestwood Painting"
baseURL = "https://crestwoodpainting.com/"
paginate = 10
timeout = "100s"
googleAnalytics = "G-Y229K0TNJR"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true

[taxonomies]
category = "categories"
categories = ["Interior", "Exterior", "Cabinets", "Commercial"]
tag = "tags"
tags = ["Products", "Tips", "Color", "Best Practices"]

disableKinds = ['RSS']
# 'robotsTXT' removed

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'assets'