title = "Crestwood Painting"
baseURL = "https://crestwoodpainting.com/"
pagination.pagerSize = 10
timeout = "100s"
enableEmoji = true
googleAnalytics = "G-Y229K0TNJR"
# old G (before '24) analytics: UA-1372967-1
[build]
  writeStats = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true       

[taxonomies]
categories = ["exterior", "interior", "color-tips", "good-to-know", "nitty-gritty", "feel-good", "hiring-painters", "painting-tips"]
# tag = "tags"
# tags = ["Products", "Tips", "Color", "Best Practices"]

disableKinds = ['RSS']
# 'robotsTXT' removed
enableRobotsTXT = true

[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'static'
target = 'assets'
