[goldmark]
  [goldmark.renderer]
    unsafe = true
    hardwraps = true # MK added to allow line breaks in titles i.e. Home title
  [goldmark.extensions]
    typographer = false
  [markup.goldmark.parser] # added 2-17-25 per https://tracknut.ca/tech/markdown-image-handling/
    wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.parser.attribute]
      block = true
 
[highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  style = "monokai"
  tabWidth = 2
[tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2 