[goldmark]
  [goldmark.renderer]
    unsafe = true
    hardwraps = true # MK added to allow line breaks in titles i.e. Home title
  [goldmark.extensions]
    typographer = false
[highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = false
  noClasses = false
  style = "monokai"
  tabWidth = 2
[tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2
# Added 6 lines below 9/2/23 - https://discourse.gohugo.io/t/resize-an-image-with-markdown/34833/11
#[module.mounts]
  source = 'assets'
  target = 'assets'
#[module.mounts]
  source = 'static'
  target = 'assets' 