# enable sidebar on main blog page
blogPageSidebarOn = false
# number of latest posts to show on blog sidebar
latestPosts = 3
email = "admin@crestwoodpainting.com"
phone = "816-805-4515"
copyright = "Copyright &copy; 2007 - 2024  [Crestwood Painting](https://crestwoodpainting.com/)"
logo = "/images/logo-crestwood.webp"
[nav_cta]
show = true
url = "/book-us/"
text = "Book an Estimate"
image = "/images/bgCanadaLake.webp"
[comments]
enable = false
[[socials]]
platform = "fb"
profile = "https://www.facebook.com/crestwoodpainting" 
icon = "facebook-f"
[[socials]]
platform = "X"
profile = "https://x.com/crestwoodpaint"
icon = "twitter"
[[socials]]
platform = "instagram"
profile = "https://www.instagram.com/crestwoodpainting/"
icon = "instagram"
# [[orgs]]
# platform = "PCA"
# profile = "https://www.pcapainted.org/"
# img = "[Painting Contractors Association](/images/logo-pca100.webp)
# Waldo? SW, BM, EPA?
