# enable sidebar on main blog page
blogPageSidebarOn = false
# number of latest posts to show on blog sidebar
latestPosts = 3
email = "admin@crestwoodpainting.com"
phone = "816-805-4515"
copyright = "Copyright &copy; 2007 - 2023  [Crestwood Painting](https://crestwoodpainting.com/)"
logo = "/images/logo-crestwoood-transparent.webp"
[nav_cta]
show = true
url = "/book-us/"
text = "Book an Estimate"
[comments]
enable = false
[[socials]]
platform = "facebook"
profile = "https://www.facebook.com/CrestwoodPainting" 
icon = "facebook-f" # fab fa-facebook-f
[[socials]]
platform = "X"
profile = "https://twitter.com/CrestwoodPaint"
icon = "twitter" # fab fa-twitter
[[socials]]
platform = "instagram"
profile = "https://www.instagram.com/crestwoodpainting/"
icon = "instagram" # fab fa-instagram
# [[socials]]
# platform = "pinterest"
# profile = "https://www.pinterest.com/crestwoodpaint/"
# icon = "pinterest-p" # fab fa-pinterest-p
