blogPageSidebarOn = false
blogPageTitleBkgnd = ""
latestPosts = 3
email = "admin@crestwoodpainting.com"
phone = "816-805-4515"
copyright = "Copyright &copy; 2007 - {year} [Crestwood Painting](https://crestwoodpainting.com/)"
logo = "admin/logo-cwp.jpg"
ogimage = ""
# [nav_cta]
# show = true
# url = "/book-us/"
# text = "Book an Estimate"
# image = "/"
[comments]
enable = false
[[socials]]
platform = "instagram"
profile = "https://www.instagram.com/crestwoodpainting/"
icon = "insta-crp"
[[socials]]
platform = "fb"
profile = "https://www.facebook.com/crestwoodpainting" 
icon = "fb-crp"
[[socials]]
platform = "X"
profile = "https://x.com/crestwoodpaint"
icon = "xtwitter-crp"
