[[company]]
name = "Terms & Conditions"
url = "#"
[[company]]
name = "Privacy Policy"
url = "#"
[[company]]
name = "Support"
url = "#"
[[company]]
name = "FAQ"
url = "#"
[[links]]
name = "About"
url = "#"
[[links]]
name = "Services"
url = "#"
[[links]]
name = "Blogs"
url = "#"
[[links]]
name = "Contact"
url = "#"